	<header id="headerimgs">
			<div id="headerimg1" class="headerimg"></div>
			<div id="headerimg2" class="headerimg"></div>
          <div id="nav-outer">
             <h1 class="logo">Martín Palottini</h1>
		    
          </div>   
 	</header>
  <section>
      <ul id="switchlang" class="text-center">
        <li><a href="index.php?contenido=inicio&amp;lang=es">Espa&ntilde;ol</a> </li>
	      <li><a href="index.php?contenido=inicio&amp;lang=en">English</a></li>
		  </ul>
  </section>
