<header id="headerimgs" class="cabecera-todas">
		<!--div id="headerimg1" class="headerimg"></div>
		<div id="headerimg2" class="headerimg"></div-->
		<h1 class="logo float-left miti"><a href="index.php?contenido=inicio">Martín Palottini</a></h1>
		<ul id="switchlang" class="text-right float-right miti">
            <li><a href="#" id="idiomaEs">ES</a> | </li> 
            <li><a href="#" id="idiomaEn">EN</a></li>
        </ul>
</header>
