	<header id="headerimgs">
			<div id="headerimg1" class="headerimg"></div>
			<div id="headerimg2" class="headerimg"></div>

            <div id="nav-outer">
	             <ul id="switchlang" class="text-right float-right miti">
	            	<li><a href="#" id="idiomaEs">ES</a> | </li> 
	            	<li><a href="#" id="idiomaEn">EN</a></li>
	    		</ul>
	             <h1 class="logo">Martín Palottini</h1>
	 	    <?php 
				include('includes/navegacion.inc'); 
			?>
           </div>   
 	</header>
